import { defineConfig, presetUno, presetAttributify, presetIcons } from 'unocss';

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
  ],
  shortcuts: {
    'flex-center': 'flex items-center justify-center',
    'flex-between': 'flex items-center justify-between',
    'badge-neutral': 'bg-zinc-500/10 text-zinc-300 border border-zinc-500/20 px-2 py-0.5 rounded text-[10px] font-medium',
    'badge-dark': 'bg-black text-white border border-zinc-800 px-2 py-0.5 rounded text-[10px] font-medium',
    'badge-light': 'bg-white text-black border border-zinc-200 px-2 py-0.5 rounded text-[10px] font-medium',
  },
  safelist: [
    'text-black',
    'text-white',
    'text-zinc-950',
    'text-zinc-900',
    'text-zinc-800',
    'text-zinc-700',
    'text-zinc-600',
    'text-zinc-500',
    'text-zinc-400',
    'text-zinc-300',
    'text-zinc-200',
    'text-zinc-100',
    'bg-black',
    'bg-white',
    'bg-zinc-950',
    'bg-zinc-900',
    'bg-zinc-850',
    'bg-zinc-800',
    'bg-zinc-700',
    'bg-zinc-200',
    'bg-zinc-100',
    'bg-zinc-50',
    'border-zinc-900',
    'border-zinc-800',
    'border-zinc-700',
    'border-zinc-600',
    'border-zinc-300',
    'border-zinc-200',
    'border-zinc-100',
  ],
});
